Add Notion (proprietary) vs AppFlowy (open source)
staltz/ttosa pull request #14
Opened 2022-09-03 19:21 UTC by janriemer

This adds Notion vs AppFlowy to the dataset.
Notion/AppFlowy is a project management and note-taking software.

Source for Notion:
https://en.wikipedia.org/wiki/Notion_(productivity_software)
Notion's first release has no specific date. Only the year is known (2016), so we use the date 2016-01-01

Source for AppFlowy:
https://www.appflowy.io/
Initial release:
https://github.com/AppFlowy-IO/AppFlowy/releases/tag/0.0.1

2022-09-05 11:17 UTC, staltz commented
Thanks! This is a perfect example. I'll change the birth date of AppFlowy to 2021-06-16 because that's its initial commit: https://github.com/AppFlowy-IO/AppFlowy/commit/a4fb87713a8488b947920730808ae263e9aff7cb

2022-09-05 11:18 UTC, staltz requested changes

2022-09-05 11:18 UTC, staltz commented on data.csv
> +Notion,2016-01-01,AppFlowy,2021-11-13,2143 days
```suggestion
Notion,2016-01-01,AppFlowy,2021-06-16,1993 days
```

2022-09-06 05:30 UTC, janriemer commented
Thanks! I committed your suggested changes. :+1:

2022-09-06 07:24 UTC, merged